import type { Metadata } from 'next';

import './_ui/global.css';
import { openSans } from './_ui/fonts';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
  }

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en" className={openSans.className}>
        <body>{children}</body>
      </html>
    )
  }